name: Crowdin translations progress
on:
  workflow_dispatch:
    #定义需要输入的参数
    inputs:
      channelId:
        #对该参数名的描述
        description: "The channel id to send message to "
        required: false
        default: "C045TT24JRJ"
        type: string
jobs:
  # github Readme 添加crowdin翻译进度，目前通过 pr 的方式 在 crowdin-translations-progress-action 目录生成 
  crowdin-translations-progress:
    runs-on: ubuntu-latest
    outputs:
      vi: ${{ steps.crowdin_translations.outputs.vi }}
      tr: ${{ steps.crowdin_translations.outputs.tr }}
      th: ${{ steps.crowdin_translations.outputs.th }}
      ms: ${{ steps.crowdin_translations.outputs.ms }}
      ko: ${{ steps.crowdin_translations.outputs.ko }}
      ja: ${{ steps.crowdin_translations.outputs.ja }}
      id: ${{ steps.crowdin_translations.outputs.id }}
      en: ${{ steps.crowdin_translations.outputs.en }}
      ar: ${{ steps.crowdin_translations.outputs.ar }}
      zh-TW: ${{ steps.crowdin_translations.outputs.zh-TW }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Output Crowdin translations progress
        id: crowdin_translations
        uses: zhangfeng-ola/crowdin-translations-progress-action@dev
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          CROWDIN_BASE_URL: ${{ secrets.CROWDIN_BASE_URL }}
    
  send-slack-message:
    runs-on: ubuntu-latest
    if: ${{ !failure() && !cancelled() }}
    needs: [crowdin-translations-progress]
    outputs:
      ts: ${{ steps.send_message.outputs.ts }}
    steps:
      - name: Format slack message
        id: format-slack-message
        run: |
          echo "------------------------------------------------------------"
          echo ${{ needs.crowdin-translations-progress.outputs.vi }}
          echo ${{ needs.crowdin-translations-progress.outputs.en }}
          echo ${{ needs.crowdin-translations-progress.outputs.ja }}
          
      - name: Slack Send Message
        id: send_message
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ github.event.inputs.channelId }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<!channel> :open_mouth: *翻译进度提醒: *"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "越南语 vi 翻译进度 ${{ needs.crowdin-translations-progress.outputs.vi }}%"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "去翻译",
                      "emoji": true
                    },
                    "style": "danger",
                    "value": "click_me_123",
                    "url": "https://olaparty.crowdin.com/u/projects/17/l/vi",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "泰语 th 翻译进度 ${{ needs.crowdin-translations-progress.outputs.th }}%"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "去翻译",
                      "emoji": true
                    },
                    "style": "danger",
                    "value": "click_me_123",
                    "url": "https://olaparty.crowdin.com/u/projects/17/l/th",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "马来语 ms 翻译进度 ${{ needs.crowdin-translations-progress.outputs.ms }}%"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "去翻译",
                      "emoji": true
                    },
                    "style": "danger",
                    "value": "click_me_123",
                    "url": "https://olaparty.crowdin.com/u/projects/17/l/ms",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "韩语 ko 翻译进度 ${{ needs.crowdin-translations-progress.outputs.ko }}%"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "去翻译",
                      "emoji": true
                    },
                    "style": "danger",
                    "value": "click_me_123",
                    "url": "https://olaparty.crowdin.com/u/projects/17/l/ko",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "日本语 ja 翻译进度 ${{ needs.crowdin-translations-progress.outputs.ja }}%"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "去翻译",
                      "emoji": true
                    },
                    "style": "danger",
                    "value": "click_me_123",
                    "url": "https://olaparty.crowdin.com/u/projects/17/l/ja",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "印尼语 id 翻译进度 ${{ needs.crowdin-translations-progress.outputs.id }}%"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "去翻译",
                      "emoji": true
                    },
                    "style": "danger",
                    "value": "click_me_123",
                    "url": "https://olaparty.crowdin.com/u/projects/17/l/id",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "英语 en 翻译进度 ${{ needs.crowdin-translations-progress.outputs.en }}%"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "去翻译",
                      "emoji": true
                    },
                    "style": "danger",
                    "value": "click_me_123",
                    "url": "https://olaparty.crowdin.com/u/projects/17/l/en",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "阿拉伯语 ar 翻译进度 ${{ needs.crowdin-translations-progress.outputs.ar }}%"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "去翻译",
                      "emoji": true
                    },
                    "style": "danger",
                    "value": "click_me_123",
                    "url": "https://olaparty.crowdin.com/u/projects/17/l/ar",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "繁体中文 zh-TW 翻译进度 ${{ needs.crowdin-translations-progress.outputs.zh-TW }}%"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "去翻译",
                      "emoji": true
                    },
                    "style": "danger",
                    "value": "click_me_123",
                    "url": "https://olaparty.crowdin.com/u/projects/17/l/zh-TW",
                    "action_id": "button-action"
                  }
                }
              ]
            } 
