name: Crowdin translations progress
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  # github Readme 添加crowdin翻译进度，目前通过 pr 的方式 在 crowdin-translations-progress-action 目录生成 
  crowdin-translations-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Crowdin translations progress markdown
        id: crowdin_translations
        uses: zhangfeng-ola/crowdin-translations-progress-action@dev
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          CROWDIN_BASE_URL: ${{ secrets.CROWDIN_BASE_URL }}

      - name: Check Crowdin Result
        run: ｜
          echo ${{ steps.crowdin_translations.outputs.languages }}
          echo ${{ steps.crowdin_translations.outputs.en }}
          echo "hello done"
