name: Crowdin translations progress
on:
  workflow_dispatch:
    #定义需要输入的参数
    inputs:
      # 第一个参数名叫prbody
      channelId: 
        #对该参数名的描述
        description: "The channel id to send message to "
        # 必须参数
        required: true
        type: string
jobs:
  # github Readme 添加crowdin翻译进度，目前通过 pr 的方式 在 crowdin-translations-progress-action 目录生成 
  crowdin-translations-progress:
    runs-on: ubuntu-latest
    outputs:
      vi: ${{ steps.crowdin_translations.outputs.vi }}
      tr: ${{ steps.crowdin_translations.outputs.tr }}
      th: ${{ steps.crowdin_translations.outputs.th }}
      ms: ${{ steps.crowdin_translations.outputs.ms }}
      ko: ${{ steps.crowdin_translations.outputs.ko }}
      ja: ${{ steps.crowdin_translations.outputs.ja }}
      id: ${{ steps.crowdin_translations.outputs.id }}
      en: ${{ steps.crowdin_translations.outputs.en }}
      ar: ${{ steps.crowdin_translations.outputs.ar }}
      zh-TW: ${{ steps.crowdin_translations.outputs.zh-TW }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Crowdin translations progress markdown
        id: crowdin_translations
        uses: zhangfeng-ola/crowdin-translations-progress-action@dev
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          CROWDIN_BASE_URL: ${{ secrets.CROWDIN_BASE_URL }}
    
  send-slack-message:
    runs-on: ubuntu-latest
    needs: [crowdin-translations-progress]
    outputs:
      ts: ${{ steps.send_message.outputs.ts }}
    steps:
      - name: Format slack message
        id: format-slack-message
        run: |
          formattedSlackMessage="hello ${{ needs.crowdin-translations-progress.outputs.vi  }}"
          echo "formatted-slack-message=${formattedSlackMessage}" >> $GITHUB_OUTPUT
      - name: Slack Send Message
        id: send_message
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ github.event.inputs.channelId }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "执行结果: ${{ steps.format-slack-message.outputs.formatted-slack-message }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": " Github 执行结果: ${{ job.status }},\n$ Next Line: {{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            } 
