name: Slack Message Demo

on:
  workflow_dispatch: 
    inputs:
      channelId:
        description: The channel id to send message to 
        required: true
        type: string
        default:

jobs:
  # before_send_message_demo:
  #   steps:
  #     - name: Before send
  #       run: echo "This step will always run --> Before send"

  send_message_demo:
    uses: ./.github/workflows/slack_message_api.yml
    with:
      # Slack channel id, channel name, or user id to post message.
      # See also: https://api.slack.com/methods/chat.postMessage#channels
      channelId: ${{ github.event.inputs.channelId }}
      botToken: ${{ secrets.SLACK_BOT_TOKEN }}

  # after_send_message_demo:
  #   needs: [before_send_message_demo, send_message_demo]
  #   steps:
  #     - name: Before send
  #       run: echo "This step will always run --> Before send"
