name: Crowdin translations progress
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  crowdin-translations-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Crowdin translations progress markdown
        uses: benjaminjonard/crowdin-translations-progress-action@1.0.5
        with:
          languages_per_row: 10
          minimum_completion_percent: 80
          file: README.md
        env:
          CROWDIN_PROJECT_ID: 17
          CROWDIN_PERSONAL_TOKEN: 9651745ba4056004051deb656ef3df4bd9c3d0634eaf45fc6bb6b3e91b5534bdc27718d9c9ddf29e
          CROWDIN_BASE_URL: https://olaparty.crowdin.com/api/v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Update Crowdin translations progress
          body: Update Crowdin translations progress by [Crowdin translations progress](https://github.com/benjaminjonard/crowdin-translations-progress-action) GitHub action
          commit-message: Update Crowdin translations progress
          branch: crowdin-translations-progress-action
