name: Slack Message Api

on:
  workflow_dispatch: 
    #定义需要输入的参数
    inputs:
      # 第一个参数名叫prbody
      channelId: 
        #对该参数名的描述
        description: "The channel id to send message to "
        # 必须参数
        required: true
        type: string
jobs:
  send_message_to_channel:

    outputs:
      ts: ${{ steps.send_message.outputs.ts }}

    runs-on: ubuntu-latest
    steps:
      - name: Slack Send Message
        id: send_message
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ github.event.inputs.channelId }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "执行结果: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": " Github 执行结果: ${{ job.status }},\n$ Next Line: {{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            } 
         
